"""
FastAPI server for the Customer Support Triage RL Environment.

Endpoints:
  POST /reset   - Start a new episode
  POST /step    - Submit a triage action
  GET  /state   - Get current environment state
  GET  /health  - Health check
  GET  /web     - Web interface
  GET  /docs    - Swagger UI (auto-generated by FastAPI)
  WS   /ws/{session_id} - WebSocket for low-latency interaction
"""

from __future__ import annotations

import json
import logging
import os
import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import uvicorn
from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.responses import HTMLResponse

# Allow imports from repo root when running as server/app.py
_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from models import (
    EnvironmentState,
    ResetRequest,
    StepRequest,
    TriageObservation,
)
from server.customer_support_env import CustomerSupportEnv

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Session registry
# ---------------------------------------------------------------------------

_sessions: dict[str, CustomerSupportEnv] = {}


def _get_or_create_env(session_id: str) -> CustomerSupportEnv:
    if session_id not in _sessions:
        env = CustomerSupportEnv()
        env.session_id = session_id
        _sessions[session_id] = env
    return _sessions[session_id]


# ---------------------------------------------------------------------------
# Default global environment (for single-client usage)
# ---------------------------------------------------------------------------

_default_env = None

def get_default_env():
    global _default_env
    if _default_env is None:
        logger.info("Initializing default environment...")
        _default_env = CustomerSupportEnv()
        logger.info("Environment initialized successfully!")
    return _default_env

# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Customer Support Triage environment starting up...")
    # Don't initialize here - lazy load on first request
    yield
    logger.info("Shutting down environment server.")


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Customer Support Triage RL Environment",
    description=(
        "Real-world customer support ticket triage environment for the "
        "Meta-PyTorch-HuggingFace OpenEnv Hackathon Round 1. "
        "The agent learns to classify, prioritize, and route support tickets."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# HTTP Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", tags=["System"])
def health_check() -> dict[str, str]:
    """Health check endpoint for Docker and load balancers."""
    return {"status": "ok", "environment": "customer-support-triage", "version": "0.1.0"}


@app.post("/reset", response_model=TriageObservation, tags=["Environment"])
def reset_episode(request: ResetRequest) -> TriageObservation:
    """
    Start a new episode.

    - **difficulty**: `easy` | `medium` | `hard`
    - **seed**: optional integer for reproducibility
    """
    try:
        obs = get_default_env().reset(difficulty=request.difficulty, seed=request.seed)
        return obs
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/step", response_model=TriageObservation, tags=["Environment"])
def step_environment(request: StepRequest) -> TriageObservation:
    """
    Submit a triage action for the current ticket.

    Returns the next observation, reward, and done flag.
    """
    try:
        obs = get_default_env().step(request.action)
        return obs
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.get("/state", response_model=EnvironmentState, tags=["Environment"])
def get_state() -> EnvironmentState:
    """Get a snapshot of the current environment state."""
    return get_default_env().state()


# ---------------------------------------------------------------------------
# Web interface
# ---------------------------------------------------------------------------

_WEB_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Customer Support Triage RL Environment</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 0; padding: 0;
         background: #0f0f1a; color: #e0e0ff; }
  .hero { background: linear-gradient(135deg,#1a1a3e,#2d1b69);
          padding: 60px 40px; text-align: center; }
  .hero h1 { font-size: 2.4rem; margin: 0 0 12px; color: #a78bfa; }
  .hero p  { font-size: 1.1rem; color: #c4b5fd; max-width: 700px; margin: 0 auto 24px; }
  .badge { display: inline-block; background: #7c3aed; border-radius: 20px;
           padding: 4px 14px; font-size: .85rem; margin: 4px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit,minmax(280px,1fr));
          gap: 20px; padding: 40px; max-width: 1100px; margin: 0 auto; }
  .card { background: #1e1e3a; border: 1px solid #3b2d6e; border-radius: 12px;
          padding: 24px; }
  .card h2 { margin: 0 0 10px; color: #a78bfa; font-size: 1.1rem; }
  .card p  { color: #9ca3af; font-size: .9rem; line-height: 1.6; margin: 0; }
  .btn { display: inline-block; margin-top: 12px; background: #7c3aed;
         color: white; padding: 8px 20px; border-radius: 8px;
         text-decoration: none; font-size: .9rem; }
  .btn:hover { background: #6d28d9; }
  .level { display: flex; justify-content: space-between; margin: 8px 0;
           font-size: .85rem; }
  .bar { height: 8px; background: #3b2d6e; border-radius: 4px; margin: 4px 0; }
  .bar-fill { height: 100%; border-radius: 4px; }
  code { background: #2d2d4a; padding: 2px 6px; border-radius: 4px;
         font-size: .85rem; color: #c084fc; }
  footer { text-align: center; padding: 20px; color: #6b7280; font-size: .85rem; }
</style>
</head>
<body>
<div class="hero">
  <h1>🎯 Customer Support Triage RL</h1>
  <p>Real-world reinforcement learning environment for the
     Meta-PyTorch-HuggingFace OpenEnv Hackathon Round 1.
     Train AI agents to classify, prioritize, and route support tickets.</p>
  <span class="badge">🏆 OpenEnv Hackathon</span>
  <span class="badge">🤖 Reinforcement Learning</span>
  <span class="badge">📩 Real-World Task</span>
</div>
<div class="grid">
  <div class="card">
    <h2>📖 API Documentation</h2>
    <p>Explore all endpoints with interactive Swagger UI. Test <code>reset</code>,
       <code>step</code>, and <code>state</code> directly in your browser.</p>
    <a class="btn" href="/docs">Open Docs →</a>
  </div>
  <div class="card">
    <h2>🎮 Difficulty Levels</h2>
    <div class="level"><span>Easy  (5 tickets)</span><span>&gt;0.85</span></div>
    <div class="bar"><div class="bar-fill" style="width:85%;background:#22c55e"></div></div>
    <div class="level"><span>Medium (10 tickets)</span><span>&gt;0.70</span></div>
    <div class="bar"><div class="bar-fill" style="width:70%;background:#f59e0b"></div></div>
    <div class="level"><span>Hard  (15 tickets)</span><span>&gt;0.50</span></div>
    <div class="bar"><div class="bar-fill" style="width:50%;background:#ef4444"></div></div>
  </div>
  <div class="card">
    <h2>⚡ Quick Start</h2>
    <p>Reset episode:<br>
       <code>POST /reset {"difficulty":"easy"}</code><br><br>
       Take action:<br>
       <code>POST /step {"action": {...}}</code><br><br>
       Check state:<br>
       <code>GET /state</code>
    </p>
  </div>
  <div class="card">
    <h2>🔌 WebSocket</h2>
    <p>Low-latency WebSocket interface for real-time agent interaction.
       Connect to <code>ws://host/ws/{session_id}</code> and send JSON messages
       with <code>"type": "reset"</code> or <code>"type": "step"</code>.</p>
  </div>
  <div class="card">
    <h2>📊 Routing Categories</h2>
    <p>
      <code>billing</code> · <code>technical</code> · <code>feature</code>
      · <code>feedback</code> · <code>spam</code><br><br>
      Urgency: <code>low</code> · <code>medium</code> · <code>high</code>
      · <code>critical</code>
    </p>
  </div>
  <div class="card">
    <h2>💡 Reward Structure</h2>
    <p>Dense rewards per ticket. Correct route: <code>+0.50</code>,
       correct urgency: <code>+0.25</code>, difficulty: <code>+0.10</code>,
       priority in range: <code>+0.05</code>. Episode bonus: <code>+0.40</code>
       for perfect episode.</p>
  </div>
</div>
<footer>Customer Support Triage RL Environment v0.1.0 · OpenEnv Hackathon Round 1</footer>
</body>
</html>
"""


@app.get("/web", response_class=HTMLResponse, tags=["System"])
def web_interface() -> HTMLResponse:
    """Web interface for the environment."""
    return HTMLResponse(content=_WEB_HTML)


@app.get("/", response_class=HTMLResponse, tags=["System"])
def root() -> HTMLResponse:
    """Root endpoint - shows web interface."""
    return HTMLResponse(content=_WEB_HTML)


# ---------------------------------------------------------------------------
# WebSocket endpoint
# ---------------------------------------------------------------------------

@app.websocket("/ws/{session_id}")
async def websocket_endpoint(websocket: WebSocket, session_id: str) -> None:
    """
    WebSocket endpoint for low-latency agent interaction.

    Message format (JSON):
      {"type": "reset", "difficulty": "easy", "seed": null}
      {"type": "step", "action": {<TriageAction fields>}}
      {"type": "state"}
    """
    await websocket.accept()
    env = _get_or_create_env(session_id)
    logger.info("WebSocket connected: session=%s", session_id)

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                msg: dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_text(
                    json.dumps({"error": "Invalid JSON"})
                )
                continue

            msg_type = msg.get("type")
            try:
                if msg_type == "reset":
                    difficulty = msg.get("difficulty", "easy")
                    seed = msg.get("seed")
                    obs = env.reset(difficulty=difficulty, seed=seed)
                    await websocket.send_text(obs.model_dump_json())

                elif msg_type == "step":
                    from models import TriageAction
                    action_data = msg.get("action", {})
                    action = TriageAction(**action_data)
                    obs = env.step(action)
                    await websocket.send_text(obs.model_dump_json())

                elif msg_type == "state":
                    state = env.state()
                    await websocket.send_text(state.model_dump_json())

                else:
                    await websocket.send_text(
                        json.dumps({"error": f"Unknown message type: {msg_type!r}"})
                    )
            except (ValueError, RuntimeError) as exc:
                await websocket.send_text(json.dumps({"error": str(exc)}))

    except WebSocketDisconnect:
        logger.info("WebSocket disconnected: session=%s", session_id)
        _sessions.pop(session_id, None)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    port = int(os.environ.get("PORT", 8000))
    host = os.environ.get("HOST", "0.0.0.0")
    uvicorn.run("server.app:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    main()